name: vae-gumbel-env
channels: 
  - conda-forge
  - ioam
dependencies:
  - python=2.7
  - numpy
  - holoviews
  - jupyter
  - pandas
  - matplotlib
  - seaborn
  - pip:
    - tqdm
    - packaging
    - appdirs
    - tensorflow
